### ISSUE TITLE
Linux BluetoothHCIAdapter shift precedence

### ISSUE THREAD

**Issue by iiSeymour** [TheCellule/python-bleson#26]
The Linux HCI adapter has the same shift precedence bug as per [python-hcipy issue 4](https://github.com/TheBubbleworks/python-hcipy/issues/4).

**Comment by WayneKeenan** [comment]
Please could you resubmit the PR with a non-temporal anomaly? :)

**Comment by iiSeymour** [comment]
Resubmitted :)
