### ISSUE TITLE
Bluetooth device address reversed

### ISSUE THREAD

**Issue by iiSeymour** [TheCellule/python-bleson#28]
Is reversing the bluetooth device address intentional [here](https://github.com/TheCellule/python-bleson/blob/master/bleson/core/types.py#L270)?

**Comment by WayneKeenan** [comment]
yes, addresses are passed around in little endian format.

**Comment by janh** [comment]
At least on Linux, the device addresses are actually in the wrong order, as they are already reversed here:
https://github.com/TheCellule/python-bleson/blob/8566949729706159d6cc11c0c07c63d86f74f9f3/bleson/core/hci/type_converters.py#L116 https://github.com/TheCellule/python-bleson/blob/8566949729706159d6cc11c0c07c63d86f74f9f3/bleson/providers/linux/linux_adapter.py#L86
