### ISSUE TITLE
RSSI value always the same

### ISSUE THREAD

**Issue by jacksoncaretech** [TheCellule/python-bleson#44]
The advertisement rssi value of a device seems always the same when scanning. It seems it is the last value of the manufacture data?

**Comment by WayneKeenan** [comment]
what platform are you on?

**Comment by shwetapalande** [comment]
Hi I am facing the same issue, I am running the code on Ubuntu 16.04.4 LTS
The RSSI value at times come as None or seems to be same while scanning, is it always the last bit of manufacturer data for BLE devices? how is RSSI calculated in case its a beacon?

**Comment by WayneKeenan** [comment]
I think this should now be fixed, please re-open if you still have an issue.

**Comment by hntrdglss** [comment]
Hey @WayneKeenan! I'm experiencing this issue with release v0.1.5, running on Ubuntu 18.04.2, where all my devices are returning an RSSI of -62. However, scanning with bluetoothctl returns different values (none of which are -62, in this case they are -37 and -57). Is there more information I can provide to help debug?

**Comment by Thrilleratplay** [comment]
@WayneKeenan Can this issue be reopened?

**Comment by WayneKeenan** [comment]
Fix has been merged.
