### ISSUE TITLE
MAC address reversed compared to typical notation

### ISSUE THREAD

**Issue by tazle** [TheCellule/python-bleson#46]
The MAC address gets reversed at https://github.com/TheCellule/python-bleson/blob/54f8439899141b1a3c6b4345e518c50c703aca44/bleson/core/hci/type_converters.py#L116 which makes its order reversed compared to the standard notation.

For example, with bleson I receive events with apparent address C0:B0:BE:85:14:BC. There is no vendor with C0:B0:BE prefix, but the reverse BC:14:85:BE:B0:C0 appears to be a Samsung device.

This appears to be a duplicate of #28, but the issue was not resolved there, even though the ticket was closed.

**Comment by tazle** [comment]
As noted in #28, the local address also seems to be reversed. My local address as reported by bleson appears as '2D:05:D4:EB:27:B8', but `hcitool dev` shows 'B8:27:EB:D4:05:2D'.

**Comment by WayneKeenan** [comment]
which platform are you on?

**Comment by WayneKeenan** [comment]
Thanks for pointing out a mistake, a PR would be most welcomed.

**Comment by tazle** [comment]
Linux, raspbian stretch.

**Comment by tazle** [comment]
I'll test the changes in https://github.com/tazle/python-bleson/commit/f3c6fbf70133c09d21afa37047f0d93d232c9359 locally first, then create a PR.

**Comment by tazle** [comment]
Closed by #47
