### ISSUE TITLE
PyPI release is quite old

### ISSUE THREAD

**Issue by puhitaku** [TheCellule/python-bleson#55]
The latest source code release on PyPI ([link](https://pypi.org/project/bleson/)) is old. Please release the latest one (and also in the future).

**Comment by WayneKeenan** [comment]
Yes, it is, but you can install using pip from source.

As it’s a volunteer effort I/we can’t commit to regular releases.

I admit there has been some good work on a fork that needs merging, just needs some time.

Noted and closing, thanks!
