### ISSUE TITLE
What is needed before updating Pypi version?

### ISSUE THREAD

**Issue by Thrilleratplay** [TheCellule/python-bleson#56]
As mentioned in #55, this is a volunteer effort and want to thank you for the work done.  This is by far the easier to use and fully functional library for working with BLE advertisements.  

Hower, the few issues I did have I later realized were fixed in newer versions and I believe are the same as #44 and #54.  While it is true that pip can install the fixes found on master using the VCS options, the instructions in the readme.md and in sphinx documentation all say to install using `pip3 install bleson`.  I would like to use this in a Home Assistant component implementation which prefers published libraries and cannot find any worthy substitutes for bleson.

What can I, or anyone else in the community, do to assistant in preparing the next alpha released to be published?

**Comment by WayneKeenan** [comment]
Hi,

The custom built CI environment that performs building and testing (against real hardware) for the 3 platforms and publishes the packages is currently offline and needs some TLC (by me) to bring back online.  

There is more info about the CI setup in the `Bleson CI Testing` post on the [Bleson Google Group](https://groups.google.com/d/msg/python-bleson/3fFn4alyo8s/kUaZBQXRBwAJ)

I'll see what I can do in the next few weeks, although it's been a while since I've touched it, but I think I left some decent docs for my future idiot self, so picking it up again shouldn't be too painful, fingers crossed :)

Longer term it might be an idea to have a 'pure cloud' option (e.g. Travis) way to publish at least the Linux/mac packages (without the windows build or hardware test step). That would be on me also to port the existing process, in the first instance. Not sure on timescale for that.

**Comment by WayneKeenan** [comment]
I did take a look a week or so ago but it was just a look, I didn’t get anything back up and running just yet.  

The link to the Google group post wasn’t public, it is now.

**Comment by Thrilleratplay** [comment]
@WayneKeenan I truly admire the effort to have full integration testing using real hardware for the three major platforms.  Although this seems like it is a Sisyphean task.  Each OS has continuous updates to tighten security, likely limiting the ability to automate running testing on physical devices.  This is in addition to continued updated to the Bluetooth spec, which has released 5.1 and 5.2 since #21 was introduced.  

May people has asked only for an update to the PyPi release.  No one reasonable developer is expecting it to be completely bug free and in fact may bugs have been fixed but still linger because it is assumed that the PyPi package is the latest version. 

From previous comments, you seem steadfast on requiring unit testing but would like to provide an alternative.  Why not break python-bleson into smaller, more manageable libraries?  One for parsing, which can be unit tested using Travis-CI, and one for each OS to create the hardware level socket, which can be unit tested on physical hardware.  All independent of each other If a particular OS is particularly problematic ** cough Windows cough **, it would not prevent continued use and development on OSes that are less finicky (Linux on a Raspberry Pi for example).  Would this be an adequate compromise?  If the parsing library is no longer dependent on physical hardware for CI, myself and I would assume others would be happy to write unit tests so the burden do not fall on just you.

**Comment by ukBaz** [comment]
>  Although this seems like it is a Sisyphean task

I like this analogy  :-)

However, I am not sure I agree that the solution is splitting up the library in to smaller libraries. I believe there are [many Python Bluetooth libraries ](https://github.com/ukBaz/python-bluezero/wiki)out there doing that today. Most (all?) of them also hit the problem of how can you you reasonably test them.

One advantage that Bleson has it that it has been constructed with different "providers". These are the bits that are OS specific. My suggestions is that ***if*** a "mock" provider could be created, tests could be run on a cloud CI service. This would have the advantage of being able to cover much of the testing apart from a a small piece that can only be done with real hardware.
While Wayne gets the automated testing of different hardware up and running, if there are the volunteers, release candidates could be created and the volunteers run tests on their hardware to test release candidates with the different providers.

I do not have the answer for how to create the mock provider, but that would seem to be a better avenue for the community to brainstorm IMHO.

**Comment by WayneKeenan** [comment]
I'm not really steadfast on getting the entire CI hardware test-rig working as a pre-requisite, I just need to spend some time to go over what was built and figure out a minimum to port to Travis as an initial step.   Getting the release/package scripts up and running (just for Linux, without HW test) 'offline' would be a good starting point for that, for sanities sake.   Sadly, I've not had the necessary focus.


A mock provider sounds like a very good idea, thanks @ukBaz

**Comment by WayneKeenan** [comment]
I've released v0.1.2 to PyPi.

It has had minimal testing on my Mac (unit tests) and on a Pi ZeroW (pip install and cli observer test)

Feedback welcomed.  (I do like the Sisyphean analogy too :) )

I'll close this issue and create tasks for the Travis config and a mock provider.
