### ISSUE TITLE
Is the Google Group Closed or Deleted?

### ISSUE THREAD

**Issue by askpatrickw** [TheCellule/python-bleson#57]
Is the Google Group for this project deleted or just invite only?

![image](https://user-images.githubusercontent.com/4002194/74108871-12db5200-4b33-11ea-8949-4a28e6f59da3.png)

**Comment by WayneKeenan** [comment]
It was there a few weeks ago and I set it to public a long time ago, will check.

**Comment by WayneKeenan** [comment]
Ah, I'd not made it public enough. Should be fixed now.
