### ISSUE TITLE
Configure CI

### ISSUE THREAD

**Issue by WayneKeenan** [TheCellule/python-bleson#69]
Step 1: Configure cloudy CI to perform a source dist release to PyPi on git tag creation.

Step 2: Use the mock provider to run tests in CI, prior to PyPi publication

**Comment by ukBaz** [comment]
As this hasn't been started with Travis-CI yet, I will link to https://github.com/ukBaz/python-bluezero/issues/182

Depending how the mock providers is done on a CI system, there is some functionality within Linux that helps with testing without having Bluetooth hardware. I have investigated accessing that on Travis-CI previously without much success. It might be worth having a look at other CI services to see if there is better access to `btvirt` on those.

**Comment by WayneKeenan** [comment]
Shippable CI is looking like a winner.  
This might help in the future:  http://docs.shippable.com/ci/tutorial/build-custom-ci-image/

**Comment by WayneKeenan** [comment]
Step 1 implemented in `shippable.yml` with 'stub' testing #68
