### ISSUE TITLE
Win10 64bit  pip install bleson fail

### ISSUE THREAD

**Issue by AIQIJundong** [TheCellule/python-bleson#79]
![image](https://user-images.githubusercontent.com/50572578/97769140-68450c80-1b63-11eb-82a0-db7ead891f5b.png)

**Comment by AIQIJundong** [comment]
pip install blesonwin
Collecting blesonwin
  Using cached blesonwin-0.0.11.tar.gz (3.2 MB)
    ERROR: Command errored out with exit status 1:
     command: 'd:\users\administrator\appdata\local\programs\python\python38\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Administrator\\AppData\\Local\\Temp\\pip-install-3xj9oui6\\blesonwin\\setup.py'"'"'; __file__='"'"'C:\\Users\\Administrator\\AppData\\Local\\Temp\\pip-install-3xj9oui6\\blesonwin\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\Administrator\AppData\Local\Temp\pip-pip-egg-info-_otu2bbe'
         cwd: C:\Users\Administrator\AppData\Local\Temp\pip-install-3xj9oui6\blesonwin\
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Administrator\AppData\Local\Temp\pip-install-3xj9oui6\blesonwin\setup.py", line 12, in <module>
        version_file = open('VERSION')
    FileNotFoundError: [Errno 2] No such file or directory: 'VERSION'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by WayneKeenan** [comment]
I've just released `bleson` 0.1.7 and `blesonwin` 0.1.11 to PyPi, which (should) fix this.   It did for me when I tested on Win10.

One thing to note is that only a single `blesonwin` binary wheel is created for Windows 10 64 bit for a single Python version 3.9.x.       Prior to this release both 32bit and 64 bit for Python 3.6.x and Python 3.7.x were built and uploaded to PyPi.

Please re-open if this does not work for you.
