### ISSUE TITLE
Bleson breaks after linux update (suggested workaround)

### ISSUE THREAD

**Issue by WouterGritter** [TheCellule/python-bleson#92]
After upgrading all apt packages, including switching to a new linux kernel on my Raspberry Pi 4 running a script using bleson, my script would crash with the following message: `OSError: [Errno 22] Invalid argument`

The error occurs in the `_set_filter` method in `linux_adapter.py`:
```python
def _set_filter(self, data):
    self._socket.setsockopt(socket.SOL_HCI, socket.HCI_FILTER, data)
```

The problem is seemingly identical to this issue in [pybleno](https://github.com/Adam-Langley/pybleno): https://github.com/Adam-Langley/pybleno/issues/63.

The fix seems to be to use the correct amount of padding, something which is now required (and was always the spec).

```python
filter = struct.pack("<LLLH", typeMask, eventMask1, eventMask2, opcode)
```

Should be replaced with
```python
filter = struct.pack("<LLLHxx", typeMask, eventMask1, eventMask2, opcode)
```

At least, this is what the issue over on pybleno suggests. This worked for me on [my fork](https://github.com/WouterGritter/python-bleson). However I still ran into another issue. The `set_features_filter` method stores the previous state of `HCI_FILTER` in the `_last_filter` field, and as per my testing with my usecase this always seems to be an integer `0`, instead of a 16-byte struct which was always expected and now required.

For me, the fix was to omit rolling back to the `_last_filter`, as it seems to override it fairly quickly afterwards anyways. It works for me, so I won't make a PR here because the fix is hacky and could possibly break in other use-cases (if it's expected the resetting of the filter works correctly). I'm guessing a proper fix would be to convert the return value of `self._socket.getsockopt(socket.SOL_HCI, socket.HCI_FILTER)` to a proper struct.

I'm hoping this helps. If anyone runs into this and is looking for a quick fix, in the mean time you can try my fork:
```bash
pip install git+https://github.com/WouterGritter/python-bleson.git
```

**Comment by afullagar** [comment]
Thanks for the info. It helped me with my custom python Tile bluetooth tracker for my dog. I added the padding and it started working. I dont fully understand the back end config so much appreciated.

i added the xx to this and it strated to work again. 
# allows LE advertising events
#new kernels pad 2 bytes so add xx to below
hci_filter = struct.pack("<IQHxx",0x00000010,0x4000000000000000,0)

**Comment by WayneKeenan** [comment]
Thank you for looking into this, will merge.

**Comment by WouterGritter** [comment]
Hi thanks for merging but please take a close look at the changes. Like I said it's a bit of a hacky workaround, and it involves removing the code to reset the HCI filter.

I think it requires a bit more thought before it can be used in the main branch

**Comment by WayneKeenan** [comment]
I took a look and am taking the view that because this project is still in Alpha then if the reset workaround breaks something for someone then digging deeper can occur if/when they shout. 
Thanks again for this.

**Comment by WouterGritter** [comment]
Sounds good, happy to help.
